characters = [
    "The Coterie",
    "Vlaad",
    "Bathory",
    "Alucard",
    "Rasputin"]

everyday_problems = [
    "just realized that their driver's license has expired, and they need to have it renewed",
    "has discovered that the local familiars are starting a union",
    "just found out that their Sire is not, in fact, their Sire",
    "has run out of places to dispose of bodies on the premises",
    "hasn't received an invite to tomorrow night's Elysium",
    "has discovered the house's foundation is cracked, and needs to be repaired",
    "is being audited by the IRS",
    "has made friends with the local Mormon missionaries",
    "has come down with the Blood Pox, a rare vampire disease",
    "is in a fight with the neighborhood HOA",
    "joins an MLM",
    "gets in a fight with the neighbors",
    "takes up a new hobby",
    "finds Jesus",
    "forgets how to speak English",
    "decides to go coffin shopping",
    "becomes obsessed with thrift store shopping and winds up buying a cursed item",
    "decides to go to night school",
    "is notified that the tree outside the house is the nesting site for an endangered bird species",
    "discovers online gaming",
    "puts the house on AirBnB",
    "finds out that a new, best-selling novel is based on their life story",
    "finds out that the house is infested with termites",
    "adopts a stray cat",
    "is being interviewed by 'Fangs', a popular vampire magazine",
    "joins the BTS Army",
    "goes to the dentist",
]

supernatural_problems = [
    "is celebrating their Death Day",
    "has found a flock of cockatrices roosting in the attic",
    "caught a pack of werewolves marking the nearby stop sign as their territory, and the fleabags won't stop congregating there",
    "was recorded doing something 'vampirish', and the video is going viral",
    "just discovered that the house was built on an ancient Native American burial ground",
    "heard that vampire hunters have been asking questions in the neighborhood",
    "has 'accidentally' created a new vampire",
    "just watched their doppelganger walk in the door",
    "heard that the Danse Macabre is in town, and it's raising Hell. Literally",
    "thinks that their new familiar might be a spy working for one of their enemies",
    "is in a cocoon",
    "is confronted by their nemesis",
    "is summoned by the local Vampiric Council",
    "discovers a Warlock has moved into town",
    "is invited to the International Supernatural Convention as a Keynote speaker",
    "decides to explore their passion as a vampire sommelier",
    "has angered a coven of witches by killing their cat",
    "finds out that they have been reincarnated",
    "is called upon to settle a Blood Debt",
    "finds a boogeyman in their closet",
]
